// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using airlineRider.DAL;

#nullable disable

namespace airlineRider.Migrations
{
    [DbContext(typeof(TypeContext))]
    [Migration("20260917211917_expandedTypes")]
    partial class expandedTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("airlineRider.Models.AircraftType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Iata")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("AircraftTypes");
                });

            modelBuilder.Entity("airlineRider.Models.Airport", b =>
                {
                    b.Property<string>("Icao")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("AType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Alpha2CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<double>("Elevation")
                        .HasColumnType("double precision");

                    b.Property<string>("Iata")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Icao");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("airlineRider.Models.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("airlineRider.Models.Auth.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("airlineRider.Models.Auth.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("airlineRider.Models.Country", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Alpha2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Alpha3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("IcaoPrefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("airlineRider.Models.Game.Airline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LobbyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("Name");

                    b.HasIndex("SystemUserId");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("airlineRider.Models.Game.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Details", "airlineRider.Models.Game.Lobby.Details#LobbyDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("CurrentTime")
                                .HasColumnType("timestamp without time zone");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Settings", "airlineRider.Models.Game.Lobby.Settings#LobbySettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date");

                            b1.Property<int>("StartingMoney")
                                .HasColumnType("integer");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "StarterAircraftDetails", "airlineRider.Models.Game.Lobby.StarterAircraftDetails#LobbyStarterAircraft", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("StarterAircraftAmount")
                                .HasColumnType("integer");

                            b1.Property<string>("StarterAircraftTypeIcao")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("airlineRider.Models.LiveryInfo", b =>
                {
                    b.Property<Guid>("LiveryInfoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AircraftTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkDir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LiveryInfoId");

                    b.ToTable("LiveryInfos");
                });

            modelBuilder.Entity("airlineRider.Models.Runway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportId")
                        .IsRequired()
                        .HasColumnType("character varying(4)");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean");

                    b.Property<int>("HeHeading")
                        .HasColumnType("integer");

                    b.Property<string>("HeIdent")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("LeHeading")
                        .HasColumnType("integer");

                    b.Property<string>("LeIdent")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<bool>("Lighted")
                        .HasColumnType("boolean");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("Runways");
                });

            modelBuilder.Entity("airlineRider.Models.Auth.UserRole", b =>
                {
                    b.HasOne("airlineRider.Models.Auth.SystemUser", "SystemUser")
                        .WithMany("Roles")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("airlineRider.Models.Game.Airline", b =>
                {
                    b.HasOne("airlineRider.Models.Game.Lobby", "Lobby")
                        .WithMany("LobbyMembers")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("airlineRider.Models.Auth.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("airlineRider.Models.LiveryInfo", b =>
                {
                    b.HasOne("airlineRider.Models.AircraftType", "AircraftType")
                        .WithOne("LiveryInfo")
                        .HasForeignKey("airlineRider.Models.LiveryInfo", "LiveryInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AircraftType");
                });

            modelBuilder.Entity("airlineRider.Models.Runway", b =>
                {
                    b.HasOne("airlineRider.Models.Airport", "Airport")
                        .WithMany("Runways")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("airlineRider.Models.AircraftType", b =>
                {
                    b.Navigation("LiveryInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("airlineRider.Models.Airport", b =>
                {
                    b.Navigation("Runways");
                });

            modelBuilder.Entity("airlineRider.Models.Auth.SystemUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("airlineRider.Models.Game.Lobby", b =>
                {
                    b.Navigation("LobbyMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
